CREATE TABLE attachments (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    file_name VARCHAR(255) NOT NULL,

    file_url TEXT NOT NULL,

    task_id INTEGER NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (task_id)
        REFERENCES tasks(id)
        ON DELETE CASCADE
);